# Generated by Django 2.2.6 on 2021-02-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20210211_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='book_photos'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=160, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
