# Generated by Django 2.2.6 on 2021-02-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20210216_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photo',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
