# Generated by Django 2.2.6 on 2021-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20210216_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book_photos/book_default.jpg', null=True, upload_to='book_photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
