# Generated by Django 2.2.6 on 2021-02-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_auto_20210217_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_photos/', verbose_name='Фото'),
        ),
    ]
